AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  merkle-tree 

  Sample SAM Template for merkle-tree 

Resources:
  MerkleTreeStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      # TODO update file name
      DefinitionUri: statemachine/merkle_tree.asl.json
      DefinitionSubstitutions:
        GenerateMerkleTreeInputFunction: !GetAtt GenerateMerkleTreeInputFunction.Arn
        GenerateMerkleTreeFunction: !GetAtt GenerateMerkleTreeFunction.Arn
        UploadMerkleTreeFunction: !GetAtt UploadMerkleTreeFunction.Arn
        SplitMerkleTreeFunction: !GetAtt SplitMerkleTreeFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateMerkleTreeInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateMerkleTreeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UploadMerkleTreeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SplitMerkleTreeFunction

  GenerateMerkleTreeInputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/input-generator/
      Handler: built/app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
      Environment:
        Variables:
          PINATA_API_KEY: ""
          PINATA_SECRET_API_KEY: ""

  GenerateMerkleTreeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/generator/
      Handler: built/app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
      Environment:
        Variables:
          MERKLE_TREE_BUCKET: "iroiro-wallet-campaign-merkle-trees"
      Policies:
        - S3WritePolicy:
            BucketName: "iroiro-wallet-campaign-merkle-trees"

  UploadMerkleTreeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/uploader/
      Handler: built/app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
      Environment:
        Variables:
          PINATA_API_KEY: ""
          PINATA_SECRET_API_KEY: ""
          MERKLE_TREE_BUCKET: "iroiro-wallet-campaign-merkle-trees"
      Policies:
        - S3ReadPolicy:
            BucketName: "iroiro-wallet-campaign-merkle-trees"

  SplitMerkleTreeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/splitter/
      Handler: built/app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 120
      Environment:
        Variables:
          MERKLE_TREE_BUCKET: "iroiro-wallet-campaign-merkle-trees"
          MERKLE_PROOF_BUCKET: "iroiro-wallet-campaign-merkle-proofs"
      Policies:
        - S3ReadPolicy:
            BucketName: "iroiro-wallet-campaign-merkle-trees"
        - S3WritePolicy:
            BucketName: "iroiro-wallet-campaign-merkle-proofs"

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  MerkleTreeStateMachineArn:
    Description: "Merkle Tree state machine ARN"
    Value: !Ref MerkleTreeStateMachine
  GenerateMerkleTreeInputFunction:
    Value: !GetAtt GenerateMerkleTreeInputFunction.Arn
  GenerateMerkleTreeFunction:
    Value: !GetAtt GenerateMerkleTreeFunction.Arn
  UploadMerkleTreeFunction:
    Value: !GetAtt UploadMerkleTreeFunction.Arn
  SplitMerkleTreeFunction:
    Value: !GetAtt SplitMerkleTreeFunction.Arn
  MerkleTreeStateMachineRole:
    Description: "IAM Role created for Merkle Tree state machine based on the specified SAM Policy Templates"
    Value: !GetAtt MerkleTreeStateMachineRole.Arn
