/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PoolInterface extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PoolInterface;
  clone(): PoolInterface;
  methods: {
    addStakingList(
      creator: string,
      token: string,
      paused: boolean
    ): NonPayableTransactionObject<void>;

    earned(
      account: string,
      token: string,
      totalSupply: number | string,
      decimals: number | string
    ): NonPayableTransactionObject<string>;

    stake(
      amount: number | string,
      token: string
    ): NonPayableTransactionObject<void>;

    withdraw(
      amount: number | string,
      token: string
    ): NonPayableTransactionObject<void>;

    claim(token: string): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
