/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface SingleTreasuryVesterInterfaceV1 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SingleTreasuryVesterInterfaceV1;
  clone(): SingleTreasuryVesterInterfaceV1;
  methods: {
    initialize(
      token: string,
      recipient: string,
      vestingStart: number | string | BN,
      vestingYears: number | string | BN
    ): NonPayableTransactionObject<void>;

    remainingAmount(): NonPayableTransactionObject<string>;

    redeemableAmount(): NonPayableTransactionObject<string>;

    redeem(): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
