/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { SingleTreasuryVesterInterfaceV1 } from "../SingleTreasuryVesterInterfaceV1";

export class SingleTreasuryVesterInterfaceV1__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SingleTreasuryVesterInterfaceV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SingleTreasuryVesterInterfaceV1;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "vestingStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vestingYears",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "remainingAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "redeemableAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
