/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { SocialTokenConstants } from "../SocialTokenConstants";

export class SocialTokenConstants__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<SocialTokenConstants> {
    return super.deploy(overrides || {}) as Promise<SocialTokenConstants>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SocialTokenConstants {
    return super.attach(address) as SocialTokenConstants;
  }
  connect(signer: Signer): SocialTokenConstants__factory {
    return super.connect(signer) as SocialTokenConstants__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SocialTokenConstants {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SocialTokenConstants;
  }
}

const _abi = [
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6099610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806318160ddd146038575b600080fd5b603e6054565b6040518082815260200191505060405180910390f35b6a084595161401484a0000008156fea2646970667358221220613444cd94eed03f1b1403476716ab5dd86e7b98f379d7c42f205065ac4f8a4c64736f6c63430007060033";
