/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SocialTokenConstantsInterface extends ethers.utils.Interface {
  functions: {
    "distributionRatio()": FunctionFragment;
    "hundredPercent()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "vestingRatio()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "distributionRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hundredPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestingRatio",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "distributionRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hundredPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingRatio",
    data: BytesLike
  ): Result;

  events: {};
}

export class SocialTokenConstants extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SocialTokenConstantsInterface;

  functions: {
    distributionRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    "distributionRatio()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    hundredPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    "hundredPercent()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    vestingRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    "vestingRatio()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  distributionRatio(overrides?: CallOverrides): Promise<BigNumber>;

  "distributionRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

  hundredPercent(overrides?: CallOverrides): Promise<BigNumber>;

  "hundredPercent()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  vestingRatio(overrides?: CallOverrides): Promise<BigNumber>;

  "vestingRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    distributionRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "distributionRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

    hundredPercent(overrides?: CallOverrides): Promise<BigNumber>;

    "hundredPercent()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    vestingRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "vestingRatio()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    distributionRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "distributionRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

    hundredPercent(overrides?: CallOverrides): Promise<BigNumber>;

    "hundredPercent()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    vestingRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "vestingRatio()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    distributionRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "distributionRatio()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hundredPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "hundredPercent()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vestingRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "vestingRatio()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
