/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TokenFactoryInterface extends ethers.utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateCreatorFund(address)": FunctionFragment;
    "createToken(string,string,uint16)": FunctionFragment;
    "createExclusiveToken(address,string,string,uint16,uint16)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreatorFund",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createExclusiveToken",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreatorFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createExclusiveToken",
    data: BytesLike
  ): Result;

  events: {
    "CreateToken(address,address,string,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class TokenFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenFactoryInterface;

  functions: {
    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateCreatorFund(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateCreatorFund(address)"(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createToken(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createToken(string,string,uint16)"(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createExclusiveToken(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createExclusiveToken(address,string,string,uint16,uint16)"(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  "owner()"(overrides?: CallOverrides): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateCreatorFund(
    newCreatorFund: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateCreatorFund(address)"(
    newCreatorFund: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createToken(
    name: string,
    symbol: string,
    donationRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createToken(string,string,uint16)"(
    name: string,
    symbol: string,
    donationRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createExclusiveToken(
    creator: string,
    name: string,
    symbol: string,
    donationRatio: BigNumberish,
    operationRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createExclusiveToken(address,string,string,uint16,uint16)"(
    creator: string,
    name: string,
    symbol: string,
    donationRatio: BigNumberish,
    operationRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCreatorFund(
      newCreatorFund: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateCreatorFund(address)"(
      newCreatorFund: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createToken(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createToken(string,string,uint16)"(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createExclusiveToken(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createExclusiveToken(address,string,string,uint16,uint16)"(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    CreateToken(
      token: string | null,
      creator: string | null,
      name: null,
      symbol: null
    ): TypedEventFilter<
      [string, string, string, string],
      { token: string; creator: string; name: string; symbol: string }
    >;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateCreatorFund(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateCreatorFund(address)"(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createToken(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createToken(string,string,uint16)"(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createExclusiveToken(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createExclusiveToken(address,string,string,uint16,uint16)"(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateCreatorFund(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateCreatorFund(address)"(
      newCreatorFund: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createToken(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createToken(string,string,uint16)"(
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createExclusiveToken(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createExclusiveToken(address,string,string,uint16,uint16)"(
      creator: string,
      name: string,
      symbol: string,
      donationRatio: BigNumberish,
      operationRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
