/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AudiusInterface extends ethers.utils.Interface {
  functions: {
    "followersHash(address)": FunctionFragment;
    "followersNum(address)": FunctionFragment;
    "nextTokenId()": FunctionFragment;
    "nextUserId()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "tokenIdList(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userIdList(address)": FunctionFragment;
    "generateClaimKey(uint64,uint64)": FunctionFragment;
    "isClaimable(address)": FunctionFragment;
    "getChainlinkToken()": FunctionFragment;
    "remainingAmount(address)": FunctionFragment;
    "addAudiusList(uint256,string,uint256)": FunctionFragment;
    "distributedAmount(address)": FunctionFragment;
    "claim(address)": FunctionFragment;
    "requestCheckingAddress(address,bytes32,string,string,address,uint256)": FunctionFragment;
    "fulfill(bytes32,bytes32)": FunctionFragment;
    "withdrawLink()": FunctionFragment;
    "cancelRequest(bytes32,uint256,bytes4,uint256)": FunctionFragment;
    "addressToStringTest()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "followersHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "followersNum",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextUserId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokenIdList", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "userIdList", values: [string]): string;
  encodeFunctionData(
    functionFragment: "generateClaimKey",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isClaimable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getChainlinkToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remainingAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAudiusList",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributedAmount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "requestCheckingAddress",
    values: [string, BytesLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfill",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLink",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRequest",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToStringTest",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "followersHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followersNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextUserId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userIdList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateClaimKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainlinkToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAudiusList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestCheckingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToStringTest",
    data: BytesLike
  ): Result;

  events: {
    "ChainlinkCancelled(bytes32)": EventFragment;
    "ChainlinkFulfilled(bytes32)": EventFragment;
    "ChainlinkRequested(bytes32)": EventFragment;
    "Claim(address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChainlinkCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChainlinkFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChainlinkRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Audius extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AudiusInterface;

  functions: {
    followersHash(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    "followersHash(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    followersNum(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "followersNum(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nextTokenId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "nextTokenId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    nextUserId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "nextUserId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    tokenIdList(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "tokenIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userIdList(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "userIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    generateClaimKey(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "generateClaimKey(uint64,uint64)"(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isClaimable(token: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isClaimable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getChainlinkToken(overrides?: CallOverrides): Promise<[string]>;

    "getChainlinkToken()"(overrides?: CallOverrides): Promise<[string]>;

    remainingAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "remainingAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addAudiusList(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addAudiusList(uint256,string,uint256)"(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    distributedAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "distributedAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claim(token: string, overrides?: Overrides): Promise<ContractTransaction>;

    "claim(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    requestCheckingAddress(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "requestCheckingAddress(address,bytes32,string,string,address,uint256)"(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "fulfill(bytes32,bytes32)"(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    withdrawLink(overrides?: Overrides): Promise<ContractTransaction>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    "withdrawLink()"(overrides?: Overrides): Promise<ContractTransaction>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    cancelRequest(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    "cancelRequest(bytes32,uint256,bytes4,uint256)"(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addressToStringTest(overrides?: CallOverrides): Promise<[string]>;

    "addressToStringTest()"(overrides?: CallOverrides): Promise<[string]>;
  };

  followersHash(arg0: string, overrides?: CallOverrides): Promise<string>;

  "followersHash(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  followersNum(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "followersNum(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

  "nextTokenId()"(overrides?: CallOverrides): Promise<BigNumber>;

  nextUserId(overrides?: CallOverrides): Promise<BigNumber>;

  "nextUserId()"(overrides?: CallOverrides): Promise<BigNumber>;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  "owner()"(overrides?: CallOverrides): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  tokenIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "tokenIdList(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "userIdList(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  generateClaimKey(
    userId: BigNumberish,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "generateClaimKey(uint64,uint64)"(
    userId: BigNumberish,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isClaimable(token: string, overrides?: CallOverrides): Promise<boolean>;

  "isClaimable(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getChainlinkToken(overrides?: CallOverrides): Promise<string>;

  "getChainlinkToken()"(overrides?: CallOverrides): Promise<string>;

  remainingAmount(token: string, overrides?: CallOverrides): Promise<BigNumber>;

  "remainingAmount(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addAudiusList(
    id: BigNumberish,
    _followersHash: string,
    _followersNum: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addAudiusList(uint256,string,uint256)"(
    id: BigNumberish,
    _followersHash: string,
    _followersNum: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  distributedAmount(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "distributedAmount(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claim(token: string, overrides?: Overrides): Promise<ContractTransaction>;

  "claim(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  requestCheckingAddress(
    _oracle: string,
    _jobId: BytesLike,
    userAddress: string,
    tokenAddress: string,
    token: string,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "requestCheckingAddress(address,bytes32,string,string,address,uint256)"(
    _oracle: string,
    _jobId: BytesLike,
    userAddress: string,
    tokenAddress: string,
    token: string,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fulfill(
    _requestId: BytesLike,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "fulfill(bytes32,bytes32)"(
    _requestId: BytesLike,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows the owner to withdraw any LINK balance on the contract
   */
  withdrawLink(overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Allows the owner to withdraw any LINK balance on the contract
   */
  "withdrawLink()"(overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Call this method if no response is received within 5 minutes
   * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
   * @param _expiration The expiration generated for the request to cancel
   * @param _payment The payment specified for the request to cancel
   * @param _requestId The ID that was generated for the request to cancel
   */
  cancelRequest(
    _requestId: BytesLike,
    _payment: BigNumberish,
    _callbackFunctionId: BytesLike,
    _expiration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Call this method if no response is received within 5 minutes
   * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
   * @param _expiration The expiration generated for the request to cancel
   * @param _payment The payment specified for the request to cancel
   * @param _requestId The ID that was generated for the request to cancel
   */
  "cancelRequest(bytes32,uint256,bytes4,uint256)"(
    _requestId: BytesLike,
    _payment: BigNumberish,
    _callbackFunctionId: BytesLike,
    _expiration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addressToStringTest(overrides?: CallOverrides): Promise<string>;

  "addressToStringTest()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    followersHash(arg0: string, overrides?: CallOverrides): Promise<string>;

    "followersHash(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    followersNum(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "followersNum(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextTokenId()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextUserId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextUserId()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    tokenIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "tokenIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "userIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    generateClaimKey(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "generateClaimKey(uint64,uint64)"(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isClaimable(token: string, overrides?: CallOverrides): Promise<boolean>;

    "isClaimable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getChainlinkToken(overrides?: CallOverrides): Promise<string>;

    "getChainlinkToken()"(overrides?: CallOverrides): Promise<string>;

    remainingAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "remainingAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAudiusList(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addAudiusList(uint256,string,uint256)"(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    distributedAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "distributedAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(token: string, overrides?: CallOverrides): Promise<void>;

    "claim(address)"(token: string, overrides?: CallOverrides): Promise<void>;

    requestCheckingAddress(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "requestCheckingAddress(address,bytes32,string,string,address,uint256)"(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "fulfill(bytes32,bytes32)"(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    withdrawLink(overrides?: CallOverrides): Promise<void>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    "withdrawLink()"(overrides?: CallOverrides): Promise<void>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    cancelRequest(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    "cancelRequest(bytes32,uint256,bytes4,uint256)"(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addressToStringTest(overrides?: CallOverrides): Promise<string>;

    "addressToStringTest()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ChainlinkCancelled(id: BytesLike | null): EventFilter;

    ChainlinkFulfilled(id: BytesLike | null): EventFilter;

    ChainlinkRequested(id: BytesLike | null): EventFilter;

    Claim(from: string | null, token: string | null, amount: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    followersHash(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "followersHash(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    followersNum(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "followersNum(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextTokenId()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextUserId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextUserId()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    tokenIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "tokenIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    userIdList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "userIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    generateClaimKey(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "generateClaimKey(uint64,uint64)"(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isClaimable(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isClaimable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainlinkToken(overrides?: CallOverrides): Promise<BigNumber>;

    "getChainlinkToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    remainingAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "remainingAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAudiusList(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addAudiusList(uint256,string,uint256)"(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    distributedAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "distributedAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(token: string, overrides?: Overrides): Promise<BigNumber>;

    "claim(address)"(token: string, overrides?: Overrides): Promise<BigNumber>;

    requestCheckingAddress(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "requestCheckingAddress(address,bytes32,string,string,address,uint256)"(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "fulfill(bytes32,bytes32)"(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    withdrawLink(overrides?: Overrides): Promise<BigNumber>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    "withdrawLink()"(overrides?: Overrides): Promise<BigNumber>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    cancelRequest(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    "cancelRequest(bytes32,uint256,bytes4,uint256)"(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addressToStringTest(overrides?: CallOverrides): Promise<BigNumber>;

    "addressToStringTest()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    followersHash(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "followersHash(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    followersNum(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "followersNum(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextTokenId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nextTokenId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextUserId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nextUserId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    tokenIdList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userIdList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userIdList(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    generateClaimKey(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "generateClaimKey(uint64,uint64)"(
      userId: BigNumberish,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isClaimable(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isClaimable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainlinkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getChainlinkToken()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    remainingAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "remainingAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAudiusList(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addAudiusList(uint256,string,uint256)"(
      id: BigNumberish,
      _followersHash: string,
      _followersNum: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    distributedAmount(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "distributedAmount(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(token: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "claim(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    requestCheckingAddress(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "requestCheckingAddress(address,bytes32,string,string,address,uint256)"(
      _oracle: string,
      _jobId: BytesLike,
      userAddress: string,
      tokenAddress: string,
      token: string,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "fulfill(bytes32,bytes32)"(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    withdrawLink(overrides?: Overrides): Promise<PopulatedTransaction>;

    /**
     * Allows the owner to withdraw any LINK balance on the contract
     */
    "withdrawLink()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    cancelRequest(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Call this method if no response is received within 5 minutes
     * @param _callbackFunctionId The bytes4 callback function ID specified for the request to cancel
     * @param _expiration The expiration generated for the request to cancel
     * @param _payment The payment specified for the request to cancel
     * @param _requestId The ID that was generated for the request to cancel
     */
    "cancelRequest(bytes32,uint256,bytes4,uint256)"(
      _requestId: BytesLike,
      _payment: BigNumberish,
      _callbackFunctionId: BytesLike,
      _expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addressToStringTest(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressToStringTest()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
