/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ChainlinkRequestInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)": FunctionFragment;
    "cancelOracleRequest(bytes32,uint256,bytes4,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "oracleRequest",
    values: [
      string,
      BigNumberish,
      BytesLike,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOracleRequest",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "oracleRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOracleRequest",
    data: BytesLike
  ): Result;

  events: {};
}

export class ChainlinkRequestInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ChainlinkRequestInterfaceInterface;

  functions: {
    oracleRequest(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)"(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelOracleRequest(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelOracleRequest(bytes32,uint256,bytes4,uint256)"(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  oracleRequest(
    sender: string,
    requestPrice: BigNumberish,
    serviceAgreementID: BytesLike,
    callbackAddress: string,
    callbackFunctionId: BytesLike,
    nonce: BigNumberish,
    dataVersion: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)"(
    sender: string,
    requestPrice: BigNumberish,
    serviceAgreementID: BytesLike,
    callbackAddress: string,
    callbackFunctionId: BytesLike,
    nonce: BigNumberish,
    dataVersion: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelOracleRequest(
    requestId: BytesLike,
    payment: BigNumberish,
    callbackFunctionId: BytesLike,
    expiration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelOracleRequest(bytes32,uint256,bytes4,uint256)"(
    requestId: BytesLike,
    payment: BigNumberish,
    callbackFunctionId: BytesLike,
    expiration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    oracleRequest(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)"(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOracleRequest(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelOracleRequest(bytes32,uint256,bytes4,uint256)"(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    oracleRequest(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)"(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelOracleRequest(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelOracleRequest(bytes32,uint256,bytes4,uint256)"(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    oracleRequest(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "oracleRequest(address,uint256,bytes32,address,bytes4,uint256,uint256,bytes)"(
      sender: string,
      requestPrice: BigNumberish,
      serviceAgreementID: BytesLike,
      callbackAddress: string,
      callbackFunctionId: BytesLike,
      nonce: BigNumberish,
      dataVersion: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelOracleRequest(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelOracleRequest(bytes32,uint256,bytes4,uint256)"(
      requestId: BytesLike,
      payment: BigNumberish,
      callbackFunctionId: BytesLike,
      expiration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
