/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PointerInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "getAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;

  events: {};
}

export class PointerInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PointerInterfaceInterface;

  functions: {
    getAddress(overrides?: CallOverrides): Promise<[string]>;

    "getAddress()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getAddress(overrides?: CallOverrides): Promise<string>;

  "getAddress()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getAddress(overrides?: CallOverrides): Promise<string>;

    "getAddress()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "getAddress()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
